default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: inpay
  username: inpay
  password: inpay
  host: localhost

development:
  <<: *default
  database: inpay_dev

test:
  <<: *default
  database: inpay_test

production:
  <<: *default
